services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - $UPTIME_KUMA_DATA:/app/data
    ports:
      - $UPTIME_KUMA_HOST_PORT:3001
    restart: unless-stopped
